[package]
name = "rp-pio-usb-host"
version = "0.1.0"
edition = "2024"

[features]
rp2040 = ["embassy-rp/rp2040", "rp-pac/rp2040"]
rp235xa = ["embassy-rp/rp235xa", "rp-pac/rp235x"]
rp235xb = ["embassy-rp/rp235xb", "rp-pac/rp235x"]

[dependencies]
embassy-rp = { version = "0.10.0", features = ["defmt", "time-driver", "critical-section-impl"] }
embassy-sync = { version = "0.8.0", features = ["defmt"] }
embassy-time = { version = "0.5.1", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-usb-driver = { version = "0.2.2", features = ["defmt"] }
rp-pac = { version = "7.0.0", default-features = false }
fixed = "1.31.0"
pio = "0.3.0"
